import 'package:destino_quisquella_front/models/agency.model.dart';

final List<TravelAgency> demoAgency = [
  TravelAgency(
    id: 'ag-001',
    name: 'Caribe Travel Pro',
    logoUrl: 'assets/mainLogo.png',
    description:
        'We craft unforgettable trips across the Caribbean and beyond. Flights, hotels, tours, cruises and tailor-made packages.',
    rating: 4.7,
    reviewsCount: 892,
    phone: '+1 (809) 555-0123',
    email: 'hello@caribetravelpro.com',
    website: 'https://caribetravelpro.example',
    address: 'Av. Principal #123',
    city: 'Santo Domingo',
    country: 'República Dominicana',
    services: [
      'Flights',
      'Hotels',
      'Tours',
      'Cruises',
      'Car rental',
      'Travel insurance',
      'Custom packages',
    ],
    openingHours: {
      'Mon–Fri': '9:00–18:00',
      'Sat': '9:00–13:00',
      'Sun': 'Closed',
    },
    social: const SocialLinks(
      instagram: 'https://instagram.com/caribetravelpro',
      facebook: 'https://facebook.com/caribetravelpro',
      tiktok: 'https://tiktok.com/@caribetravelpro',
      youtube: 'https://youtube.com/@caribetravelpro',
    ),
    photos: const [
      AgencyPhoto(
        id: 'p1',
        url: 'assets/localimages/chavon_1.jpg',
        caption: 'Front desk',
      ),
      AgencyPhoto(
        id: 'p2',
        url: 'assets/localimages/chavon_2.jpg',
        caption: 'Team',
      ),
      AgencyPhoto(
        id: 'p3',
        url: 'assets/localimages/chavon_3.jpg',
        caption: 'Client lounge',
      ),
    ],
    destinations: const [
      DestinationItem(
        id: 'd1',
        title: 'Punta Cana All-Inclusive',
        country: 'República Dominicana',
        city: 'Punta Cana',
        thumbnailUrl: 'assets/localimages/punta_cana.jpg',
        tags: ['Beach', 'All-inclusive', 'Family'],
        priceFrom: 799,
        days: 4,
        rating: 4.8,
        featured: true,
      ),
      DestinationItem(
        id: 'd2',
        title: 'Cartagena Colonial Escape',
        country: 'Colombia',
        city: 'Cartagena',
        thumbnailUrl: 'assets/localimages/cartagena.jpg',
        tags: ['City', 'Culture', 'Romantic'],
        priceFrom: 649,
        days: 3,
        rating: 4.6,
      ),
      DestinationItem(
        id: 'd3',
        title: 'Cancún Adventure Pack',
        country: 'México',
        city: 'Cancún',
        thumbnailUrl: 'assets/localimages/cancun.jpg',
        tags: ['Beach', 'Adventure', 'Nightlife'],
        priceFrom: 899,
        days: 5,
        rating: 4.5,
      ),
      DestinationItem(
        id: 'd4',
        title: 'Bahamas Cruise',
        country: 'Bahamas',
        city: 'Nassau',
        thumbnailUrl: 'assets/localimages/bahamas.jpg',
        tags: ['Cruise', 'Relax', 'Premium'],
        priceFrom: 1099,
        days: 7,
        rating: 4.7,
        featured: true,
      ),
    ],
  ),
];
